
server:
  port:8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/dmeo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:generator/mapper/*.xml
  type-aliases-package: com.zenki.dataplus.pmi.dao.generated.entity


#jwt认证白名单
com:
  ruoyi:
    project:
      whiteList: /testWhiteList/hello,/testWhiteList/sida

